# Generated by Django 5.0.2 on 2024-02-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone_no', models.IntegerField()),
                ('user_address', models.CharField(max_length=100)),
                ('password1', models.CharField(max_length=30)),
                ('password2', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=50)),
                ('shop_name', models.CharField(max_length=50)),
                ('shop_address', models.CharField(max_length=100)),
                ('shop_licience', models.ImageField(blank=True, upload_to='licience')),
                ('vendor_email', models.EmailField(max_length=254)),
                ('vendor_phone', models.IntegerField()),
                ('pswd1', models.CharField(max_length=30)),
                ('pswd2', models.CharField(max_length=30)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
